[package]
name = "puzller-solver"
version = "0.1.0"
authors = ["mugi-uno <mugi.uno@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.18"
wasm-bindgen = "0.2"
enum-iterator = "0.7.0"
colored = "2.0.0"